### PR TITLE
[CIVIS-7585] Fix terminal access

### PR DESCRIPTION
**Pull request by mheilman**
This fixes terminal access. At some point, the notebook code changed to not automatically create a terminal when, e.g., `/terminals/1` was accessed. This updated code creates a terminal if one doesn't already exist before going to the terminal page.

While there's a [TerminalList.new_terminal()](https://github.com/jupyter/nbclassic/blob/b6257e966f47951b49f661bd129de1fc794079c2/nbclassic/static/tree/js/terminallist.js#L46) function, it does not appear to be accessible from the `env` variable that the extension is provided, so this code follows what that function does by posting to `/api/terminals`, etc.

Note: When we update to notebook 7, we'll probably have to rewrite a lot of this, so this is only temporary.

[Here's](https://platform.civisanalytics.com/spa/#/notebooks/36180?expanded=true) an internal test notebook in Platform.

---

- [x] (For Civis employees only) Reference to a relevant ticket in the pull request title
- [x] Changelog entry added to `CHANGELOG.md` at the repo's root level
- [x] Description of change in the pull request description
- [x] If applicable, unit tests have been added and/or updated
- [x] The CircleCI builds have all passed

### CODE REVIEW

**Comment by mheilman** [comment]
I'm no JavaScript expert, so there might be a better way to do this. Also, please let me know if the JS isn't following conventions, etc.

**Review by jacksonlee-civis — COMMENTED** [review]
Thank you for fixing the terminal! `:hero:` I cloned Mike's test Platform notebook, verified that the terminal could successfully be accessed from the running notebook, and checked that the internal test Docker image code does match the proposed code changes from this pull request. So LGTM from a user's point of view!

I'm not a JS expert, either, so will let Leanne be the final judge for actual approval.

**Review by leanne73 — APPROVED** [review]
LGTM!

**Comment by mheilman** [comment]
As a followup, I made a new release: https://pypi.org/project/civis-jupyter-notebook/2.2.1/

**Pull request merged**
