### PR TITLE
[DSRD-700] In Which We Install Requirements With the --upgrade Flag

### PR DESCRIPTION
**Pull request by waltaskew**
I've got a notebook: 
https://platform.civisanalytics.com/spa/#/notebooks/6241
which is failing to start with:
```
pip._vendor.pkg_resources.ContextualVersionConflict: (civis 1.9.0 (/opt/conda/lib/python3.6/site-packages), Requirement.parse('civis<2.0.0,>=1.9.2'), {'gfk'})
```
because it's trying to install version 1.9.2 of the civis client, but 1.9.0 is already installed on the docker image. I think we need to do our pip install with the --upgrade flag to allow it to install a higher version of what's already present.

Relatedly, do we have a docker image for notebooks that just supplies python, pip and nothing else that expects the user to bring all the other packages themselves?

@salilgupta1 are you a good person to look at this?

### CODE REVIEW

**Comment by salilgupta1** [comment]
This looks fine to me - I'd just test it thoroughly.

I don't think we have a docker image for notebooks that just supplies python and pip. If you want to use a notebook with platform you need this package installed.

**Comment by waltaskew** [comment]
> I don't think we have a docker image for notebooks that just supplies python and pip. If you want to use a notebook with platform you need this package installed.

I mean just python & pip as opposed to civis-jupyter-python3 which is python & pip and and whole bunch of other packages, including a version of the civis client conflicting with the one I want to install!

**Comment by waltaskew** [comment]
Is there anything I need to do to get this up on pypi?

**Comment by salilgupta1** [comment]
> I mean just python & pip as opposed to civis-jupyter-python3 which is python & pip and and whole bunch of other packages, including a version of the civis client conflicting with the one I want to install!

I think you should just upgrade the `civis-jupyter-python3` image to point to the newest version of datascience-python

**Comment by waltaskew** [comment]
> I think you should just upgrade the civis-jupyter-python3 image to point to the newest version of datascience-python

I'd prefer a solution that allows me to install packages newer than what's on datascience-python.
I ended up creating my own notebook image that has the package versions I want.

**Pull request closed without merging**
